name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: setup-go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod

      - name: install-task
        run: go install github.com/go-task/task/v3/cmd/task@latest

      - name: check
        run: task check

      - name: build
        run: task build

      - name: generate
        run: task generate

      - name: check-dirty
        run: task check:dirty
